### ISSUE TITLE
Categories show up as a single channel

### ISSUE THREAD

**Issue by grapeslush** [muxpie/livestream-companion#2]
Hello,

After adding my source, filtering out unwanted categories, and then heading over to channels, all the categories show up as a single channel rather than all the channels underneath the categories. They show up the same way when trying to import them to Plex. 

See screenshot below.

<img width="1256" alt="Xnapper-2023-08-22-07 59 52" src="https://github.com/muxpie/livestream-companion/assets/113303741/42a6e199-ac61-40b5-bd0a-79d9f4136a1e">

**Comment by grapeslush** [comment]
This was not a real issue. Just a problem with the playlist.

**Comment by muxpie** [comment]
@grapeslush Great to hear you were able to figure it out! Thanks for letting us know and closing the issue!

**Comment by grapeslush** [comment]
Hey, so I hate to re-open this. But I'm running into this again and cannot for the life of me figure out why.

**Comment by grapeslush** [comment]
FYI, figured this out. I had the app data directory contained within a directory that another container had access to and permissions where changed. It could not write any data. But no errors were being presented and it continued to show the high level group channels. 

Not sure if it might be worth adding some additional logging, but just wanted to share.

**Comment by muxpie** [comment]
Hi @grapeslush ,
thanks for sharing your findings, that is an interesting one. We will try to simulate the issue and, if possible, create some specific logs to help in the troubleshooting.
