### ISSUE TITLE
FFMPEG Process Stopped Unexpectedly 

### ISSUE THREAD

**Issue by grapeslush** [muxpie/livestream-companion#3]
As you can see, I've started getting this error related to FFMPEG stopping. No changes in my environment, and everything has been working well until today. I've tried restarting the container etc to no avail. I cannot find any additional logging to try to understand why ffmpeg would be failing.

![Xnapper-2023-09-13-15 31 36](https://github.com/muxpie/livestream-companion/assets/113303741/58b2aee0-97c2-46ee-b8ab-c600a5b321bb)

**Comment by muxpie** [comment]
@grapeslush Have you tried to open your stream outside with a different app? You can try too to re-add your list and if it doesn't work, then recreating the container. There is no reason for it stop working by itself after some time, so the biggest chance is that something changed in your streaming.

**Comment by muxpie** [comment]
Closing for innactivity. Please feel free to reopen in case you still have issues
