### ISSUE TITLE
where is the documentation 

### ISSUE THREAD

**Issue by coreyman2000** [muxpie/livestream-companion#6]
the config document does go anywhere

**Comment by muxpie** [comment]
Thank you for bringing up the issue regarding the lack of documentation. We acknowledge the importance of comprehensive documentation and we are planning to include it in future updates.

In the meantime, you can find initial setup instructions in the README file. Once the app is installed, the main page provides further guidance on managing the providers.

We appreciate your interest and patience as we work to improve the project.
